[package]
name = "openhistory-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
openhistory-adapters = { path = "../openhistory-adapters" }
openhistory-domain = { path = "../openhistory-domain" }
openhistory-entities = { path = "../openhistory-entities" }
openhistory-privacy = { path = "../openhistory-privacy" }
tokio.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
axuielement = { version = "0.9.1", default-features = false, features = ["async"] }

[lints]
workspace = true
