[package]
name = "openhistory-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
openhistory-domain = { path = "../openhistory-domain" }
openhistory-segmentation = { path = "../openhistory-segmentation" }
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
