[package]
name = "openhistory-summaries"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
openhistory-digest = { path = "../openhistory-digest" }
openhistory-segmentation = { path = "../openhistory-segmentation" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
openhistory-domain = { path = "../openhistory-domain" }

[lints]
workspace = true
